name: check_formatting
on: [push, pull_request]
jobs:
  formatting_verification_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Check formatting
        run: |
          black --check .
          isort --check-only .
